apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alb-maintenance-operator

images:
- name: controller
  newName: ghcr.io/k8s-operators-devops/app-maintenance-operator
  newTag: v1.0.0

resources:
- ../crd
- ../rbac/service_account.yaml
- ../rbac/leader_election_role.yaml
- ../rbac/leader_election_role_binding.yaml
- ../rbac/namespaced_manager_role.yaml
- ../rbac/namespaced_manager_role_binding.yaml
- ../manager

patches:
- path: manager_namespace_patch.yaml
  target:
    kind: Deployment
    name: alb-maintenance
