apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-maintenance
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --metrics-bind-address=0
        - --leader-elect
        - --health-probe-bind-address=:8081
        env:
        - name: OPERATOR_VERSION
          value: v1.1.0
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
