apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: app-maintenance-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: v1.1.0
    app.kubernetes.io/managed-by: kustomize
  name: alb-maintenance
  namespace: alb-maintenance-operator
