apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-maintenance-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/k8s-operators-devops/app-maintenance-operator.git
    targetRevision: v1.1.0
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: alb-maintenance-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
