apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: k8s-maintenance-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/managed-by: kustomize
  name: alb-maintenance
  namespace: maintenance-operator
