apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-maintenance-operator
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: v1.0.0
  url: https://github.com/k8s-operators-devops/app-maintenance-operator.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-maintenance-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-maintenance-operator
  targetNamespace: alb-maintenance-operator
